[workspace]
members = ["fitgirl-torrent-scrap", "count-file-size", "db-helper"]
resolver = "2"

[profile.release]
codegen-units = 1
opt-level = "s"
lto = true
strip = true

[workspace.dependencies]
db-helper = { path = "./db-helper" }
