[workspace]
members = [
    "fitgirl-torrent-scrap",
    "count-file-size",
    "db-helper",
    "export-excel",
]
resolver = "2"

[profile.release]
codegen-units = 4
opt-level = "s"
lto = "thin"
strip = true

[workspace.dependencies]
db-helper = { path = "./db-helper" }

[patch.crates-io]
polars = { git = "https://github.com/mokurin000/polars", branch = "fix/unpin-chrono" }
polars-arrow = { git = "https://github.com/mokurin000/polars", branch = "fix/unpin-chrono" }
